# Generated by Django 5.2.15 on 2026-06-21 18:13

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('extracted_claim', models.TextField()),
                ('source_input_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL')], max_length=4)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('api_name', models.CharField(max_length=64)),
                ('response_payload', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache_entries',
                'indexes': [models.Index(fields=['expires_at'], name='cache_entri_expires_38d64b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='factcheck.claim')),
            ],
            options={
                'db_table': 'claim_embeddings',
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('supported', 'Supported'), ('disputed', 'Disputed'), ('false', 'False'), ('unverifiable', 'Unverifiable')], max_length=12)),
                ('confidence_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='factcheck.claim')),
            ],
            options={
                'db_table': 'verdicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=2000)),
                ('evidence_snippet', models.TextField()),
                ('relevance_score', models.FloatField()),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='factcheck.verdict')),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['-relevance_score'],
            },
        ),
    ]
