# Generated by Django 5.2.15 on 2026-06-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='verdict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='factcheck.verdict'),
        ),
    ]
